### ISSUE TITLE
Whatsapp Beta does not show up for unread messages

### ISSUE THREAD

**Issue by eduardlleshi** [xiaogdgenuine/Doll#32]
I switched to a MacBook without a touchbar and Doll is a lifesaver when it comes to glancing at notifications with a hidden Dock.

Doll has been working great for other apps (Slack, Spark), except for Whatsapp Beta. The icon won't show up if there are any notifications.

This is my Doll setting page: 
![CleanShot 2023-06-02 at 10 34 02@2x](https://github.com/xiaogdgenuine/Doll/assets/6278258/45a6ae0b-d11c-4c2d-8fcc-f030385f3a99)

This is my Dock with Whatsapp Beta having a badge:
<img width="108" alt="CleanShot 2023-06-02 at 10 42 42@2x" src="https://github.com/xiaogdgenuine/Doll/assets/6278258/6d6e8dfa-aedc-48e9-9df8-b005484eda7c">

This is the menu (Whatsapp icon does not show up):
<img width="437" alt="CleanShot 2023-06-02 at 10 43 50@2x" src="https://github.com/xiaogdgenuine/Doll/assets/6278258/ab59aedb-5fa4-4295-bd40-5a1439769c56">

If I uncheck the `Hide icons when there are no new notifications` the apps to show up in the menu:
<img width="450" alt="CleanShot 2023-06-02 at 10 45 04@2x" src="https://github.com/xiaogdgenuine/Doll/assets/6278258/07f0b43b-e0d0-4697-be30-7098ccea9b2b">

So the Whatsapp icon does show up, but Doll somehow is not able to read the badge count from it.

**Comment by xiaogdgenuine** [comment]
Hi @eduardlleshi thanks for reporting, I suspect this is related to your system language setting, if it's no English then this bug could happen.

I fixed the bug in version 0.0.9, please download and check if it fix your problem, if not then let me know I will do a further debugging:
https://github.com/xiaogdgenuine/Doll/releases/tag/v0.0.9

**Comment by eduardlleshi** [comment]
Hi @xiaogdgenuine. Appreciate you looking into it.

I did update to 0.0.9 but the issue is still persisting. The system language is set to English. It's odd as the other apps are working as expected.

**Comment by xiaogdgenuine** [comment]
Hi @eduardlleshi I did like to help you further debug this one, how can I install WhatsApp beta in my mac? Any testing program I need to sign in?

**Comment by eduardlleshi** [comment]
I just tried the latest stable version of WhatsApp and the same is happening with Doll. You can download it [here](https://www.whatsapp.com/download).

After running it you will have to scan the QR code from your phone to sign in. If you are not a WhatsApp user don't worry about it, I'll manage without the Doll notification.

**Comment by xiaogdgenuine** [comment]
Hi @eduardlleshi I just sign up an WhatsApp account and verified in my mac, it's working, my system is latest macOS 14.
<img width="1132" alt="image" src="https://github.com/xiaogdgenuine/Doll/assets/51731239/76b8a411-acc2-4bcc-a1ea-07a72ee414aa">

Sorry I don't have clue why its no working in your mac, perhaps few months later when you upgrade the macOS version or doing some random stuffs it will be functional suddenly :P? I don't know but I will keep an eye on this, let's leave the issue open in case someone use WhatsApp got the same issue and we can share findings here.

**Comment by eduardlleshi** [comment]
Thanks for the update @xiaogdgenuine

Yeah hopefully it fixes on it's own :)

**Comment by eduardlleshi** [comment]
Hey @xiaogdgenuine! Just wanted to let you know that this was fixed on 0.0.9.1!

I don't know if it's related, but this time I didn't use the "Pick" button but searched for the app within Doll instead.
